sudo: required

language: bash

services:
  - docker

before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

install:
  - docker build -t inaetics/felix-agent . && docker push inaetics/felix-agent
